### ISSUE TITLE
How do you set a persons death is that possible?

### ISSUE THREAD

**Issue by RBLXUSER2008** [syorito-hatsuki/death-counter#10]
?????

**Comment by syorito-hatsuki** [comment]
The mod takes deaths from in-game stats, so to change it you need to manipulate with in-game stats. I'm bad with vanilla so can't help much. 

On 1.13, there exists a command for setting `/stats`, but it was removed, and as soon as I knew it was replaced with `/data`, I didn't know how to use it.

Another way that I use mostly is to change data directly from the folder
|Client|Server|
|--|--|
|`<minecraftForlder>/saves/<world>/stats/<yourUUID>.json`|`<server>/world/stats/<yourUUID>.json`|

Recommend shutdown server/world before change because I don't know where and when Minecraft can read that file for self
